//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;
using System.Xml;
using System.Xml.Serialization;
using System.IO;

namespace AssemblyCSharp
{
	[XmlRoot("AreaDB")]
	public class AreaDB
	{
		[XmlArray("Areas"),XmlArrayItem("Area")]
		public List<Area> areaDex;

		public AreaDB ()
		{
		}

		public void Save(string path)
		{
			var serializer = new XmlSerializer(typeof(AreaDB));
			using(var stream = new FileStream(path, FileMode.Create))
			{
				serializer.Serialize(stream, this);
			}
		}
		
		public static AreaDB Load(string path)
		{
			var serializer = new XmlSerializer(typeof(AreaDB));
			using(var stream = new FileStream(path, FileMode.Open))
			{
				return serializer.Deserialize(stream) as AreaDB;
			}
		}
		
		//Loads the xml directly from the given string. Useful in combination with www.text.
		public static AreaDB LoadFromText(string text) 
		{
			var serializer = new XmlSerializer(typeof(AreaDB));
			return serializer.Deserialize(new StringReader(text)) as AreaDB;
		}

		public List<Area> getAreaList() {
			return areaDex;
		}

		public int findArea(string a) {
			for (int i = 0; i < areaDex.Count; i++) {
				if (areaDex[i].getName().ToLower() == a.ToLower()) {
					return i;
				}
			}
			return -1;
		}
	}
}

