//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Xml;
using System.Xml.Serialization;
using UnityEngine;

namespace AssemblyCSharp
{
	public class Area
	{
		[XmlAttribute("name")]
		public string name;
		public Item resource;

		public Area ()
		{

		}


		//---GETTERS & SETTERS---
		public void setName(string n) {
			name = n;
		}

		public string getName() {
			return name;
		}

		public void setResource(Item r) {
			resource = r;
		}

		public Item getResource() {
			return resource;
		}
	}
}

