//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
	public class Item : MonoBehaviour
	{
		public String name;
        public int count;
		public int id;

		//public Sprite image;

		public void createItem(string a, int b) {
			name = a;
			id = b;
            count = 1;
		}

		public static bool operator ==(Item a, Item b) {
			if (a.name == b.name) {
				return true;
			} else {
				return false;
			}
		}
		public static bool operator !=(Item a, Item b) {
			if (a.name != b.name) {
				return true;
			} else {
				return false;
			}
		}

		//getters and setters
		//name shouldn't change so it doesn't need a setter
		//might need a getter though for display purpose

        public void setName(string newName)
        {
            name = newName;
        }

        public string getName() {
			return name;
		}

        public void addCount(int c)
        {
            count += c;
        }

        public void subCount(int c)
        {
            count -= c;
        }

        public void setCount(int c)
        {
            count = c;
        }

        public int getCount()
        {
            return count;
        }

        public void setID(int newID)
        {
            id = newID;
        }

        public int getID()
        {
            return id;
        }


	}
	


}

