//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;
using System.Xml;
using System.Xml.Serialization;
using System.IO;

namespace AssemblyCSharp
{
	[XmlRoot("ItemDex")]
	public class ItemDex {
	
		[XmlArray("Items"),XmlArrayItem("Item")]
		public List<Item> index;

		public ItemDex() {
			//index = Load(Path.Combine(Application.dataPath, "XML/database.xml"));
		}

		public void Save(string path)
		{
			var serializer = new XmlSerializer(typeof(ItemDex));
			using(var stream = new FileStream(path, FileMode.Create))
			{
				serializer.Serialize(stream, this);
			}
		}
		
		public static ItemDex Load(string path)
		{
			var serializer = new XmlSerializer(typeof(ItemDex));
			using(var stream = new FileStream(path, FileMode.Open))
			{
				return serializer.Deserialize(stream) as ItemDex;
			}
		}
		
		//Loads the xml directly from the given string. Useful in combination with www.text.
		public static ItemDex LoadFromText(string text) 
		{
			var serializer = new XmlSerializer(typeof(ItemDex));
			return serializer.Deserialize(new StringReader(text)) as ItemDex;
		}


		//return the count of items
		public int Count() {
			return index.Count;
		}
	
	}

}

