//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

namespace AssemblyCSharp
{
	public class Party
	{
		public List<GameObject> theParty;

		public Inventory stock;

		public Party ()
		{
			theParty = new List<GameObject>();
			stock = new Inventory();
		}

		// - Still have no clue why I would have this but
		// - SETTERS!!!!
		public void setInventory(Inventory a) {
			stock = a;
		}

		public Inventory getInventory() {
			return stock;
		}

		public List<GameObject> getMembers() {
			return theParty;
		}

		public void addMember(GameObject toAdd) {
			theParty.Add(toAdd);
		}

		public void removeMember(GameObject toRemove) {
			theParty.Remove(toRemove);
		}
	}
}

