//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace AssemblyCSharp
{
	public class Party
	{
		public List<Person> theParty;

		public Inventory stock;

		public Party ()
		{
			theParty = new List<Person>();
			stock = new Inventory();
		}

		// - Still have no clue why I would have this but
		// - SETTERS!!!!
		public void setInventory(Inventory a) {
			stock = a;
		}

		public Inventory getInventory() {
			return stock;
		}

		public List<Person> getMembers() {
			return theParty;
		}

		public void addMember(Person toAdd) {
			theParty.Add(toAdd);
		}

		public void removeMember(Person toRemove) {
			theParty.Remove(toRemove);
		}
	}
}

