//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Person
	{
		public Inventory bag;
		//public int id;
		public string name;
		public int craftSkill, gatheringSkill;

		public Area currArea;

		//Initiater
		public Person ()
		{
			bag = new Inventory();
			craftSkill = 0;
			gatheringSkill = 0;
		}

		public Person(string n, int cSkill, int gSkill) {
			name = n;
			craftSkill = cSkill;
			gatheringSkill = gSkill;
		}

		public void obtainItem(Item a) {
			bag.addItem(a);
		}

		public void dropOff(Inventory stock) {
			for (int i = 0; i < bag.Count ();  i++) {
				stock.addItem(bag.item (i));
			}
		}


		public void setArea(Area a) {
			currArea = a;
		}

		public Area getArea() {
			return currArea;
		}

		public void setName(string n) {
			name = n;
		}

		public string getName() {
			return name;
		}



	}
}

